import type { RxJsonSchema } from 'rxdb';
import { isoDate, optionalString, stringId } from './common';
import type { TransactionDoc } from '@/database/types';

export const transactionSchema: RxJsonSchema<TransactionDoc> = {
  title: 'transactions',
  version: 2,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: stringId,
    userId: stringId,
    type: { type: 'string', maxLength: 20 },
    amount: { type: 'integer', minimum: 1, maximum: 9007199254740991, multipleOf: 1 },
    categoryId: stringId,
    title: { type: 'string', maxLength: 200 },
    description: optionalString,
    date: { type: 'string', maxLength: 20 },
    paymentMethod: { type: 'string', maxLength: 40 },
    notes: optionalString,
    isRecurring: { type: 'boolean' },
    recurringId: stringId,
    createdAt: isoDate,
    updatedAt: isoDate,
    deletedAt: isoDate,
    accountId: stringId,
    isTransfer: { type: 'boolean' },
    transferGroupId: stringId,
    transferRole: { type: 'string', maxLength: 20 },
  },
  required: [
    'id',
    'userId',
    'type',
    'amount',
    'categoryId',
    'title',
    'date',
    'paymentMethod',
    'isRecurring',
    'createdAt',
    'updatedAt',
    'deletedAt',
    'accountId',
    'isTransfer',
    'transferGroupId',
    'transferRole',
  ],
  indexes: [
    'userId',
    'deletedAt',
    'date',
    'accountId',
    'categoryId',
    'transferGroupId',
    'updatedAt',
    ['userId', 'deletedAt'],
    ['categoryId', 'deletedAt'],
    ['accountId', 'deletedAt'],
  ],
};
